version: "3"
services:
  redis:
    image: redis:3
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
  mongo:
    image: mongo:4
    container_name: mongo
    hostname: mongo
    env_file:
      - conf/celery.env
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  beat:
    build: .
    image: python_image
    container_name: beat
    hostname: beat
    volumes:
      - .:/usr/src/app
    command: bash -c 'celery -A main beat'
    env_file:
      - conf/celery.env
    depends_on:
      - worker1
      - worker2
  worker1:
    image: python_image
    hostname: worker1
    container_name: worker1
    volumes:
      - .:/usr/src/app
    command: bash -c 'celery -A main worker -Q queue1'
    env_file:
      - conf/celery.env
    depends_on:
      - redis
      - mongo
  worker2:
    image: python_image
    hostname: worker2
    container_name: worker2
    volumes:
      - .:/usr/src/app
    command: bash -c 'celery -A main worker -Q queue2'
    env_file:
      - conf/celery.env
    depends_on:
      - redis
      - mongo
  flower:
    image: python_image
    hostname: flower
    container_name: flower
    command: bash -c 'celery -A main flower'
    env_file:
      - conf/celery.env
    ports:
      - "5555:5555"
    depends_on:
      - worker1
      - worker2
